services:
  - type: web
    name: dokon-boshqaruvi
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 10000
